---
stages:
  - validate
  - tag
  - changelog

include:
  - project: 'sysadmins/templates-ci'
    ref: master
    file:
      - 'yamllint.yml'
      - 'ansible-lint.yml'
      - 'ansible-syntax-check.yml'
      - 'create_tag.yml'
      - 'create_changelog.yml'
    interruptible: true
    tags:
      - ansible-ci
    only:
      refs:
        - master
