---
stages:
  - validate
  - tag
  - changelog

.template:
  interruptible: true
  stage: validate
  tags:
    - ansible-ci

yamllint:
  extends: .template
  script:
    - yamllint -c .yamllint .

ansible-lint:
  extends: .template
  script:
    - cd tests/
    - ansible-lint --parseable-severity -x deprecated -v playbook.yml

include:
  - project: 'sysadmins/templates-ci'
    ref: master
    file:
      - 'create_tag.yml'
      - 'create_changelog.yml'
    interruptible: true
    tags:
      - ansible-ci
    only:
      refs:
        - master
