---
- name: zabbix-agent | include vars/agent.yml
  include_vars: agent.yml
  when: zabbix_agent
  tags:
    - zabbix_agent
    - zabbix_install
    - zabbix_config
    - zabbix_external

- name: zabbix-agent | include validate.yml
  include: validate.yml
  tags:
    - zabbix_agent
    - zabbix_install
    - zabbix_config
    - zabbix_external

- name: zabbix-agent | include install.yml
  include: install.yml
  tags:
    - zabbix_agent
    - zabbix_install

- name: include config.yml
  include: config.yml
  tags:
    - zabbix_agent
    - zabbix_config

- name: zabbix-agent | include agent/config.yml
  include: agent/config.yml
  when: zabbix_agent_sudo
  tags:
    - zabbix_agent
    - zabbix_config

- name: zabbix-agent | include external.yml
  include: external.yml
  tags:
    - zabbix_agent
    - zabbix_config
    - zabbix_external
