---
- name: Installing the Zabbix-api package on localhost
  pip:
    name: zabbix-api
  delegate_to: localhost
  run_once: true
  tags:
    - zabbix_api
    - zabbix_api_hosts
    - zabbix_api_maintenance
    - zabbix_api_screen
    - zabbix_api_proxies

- name: Manage Zabbix Hosts
  include: api/hosts.yml
  tags:
    - zabbix_api
    - zabbix_api_hosts

- name: Manage Zabbix Maintenance
  include: api/maintenance.yml
  when: zabbix_maintenance
  tags:
    - zabbix_api
    - zabbix_api_maintenance

- name: Manage Zabbix Screen
  include: api/screen.yml
  when: zabbix_screen is defined and zabbix_screen |length > 0
  tags:
    - zabbix_api
    - zabbix_api_screen

- name: Manage Zabbix Proxies
  include: api/proxies.yml
  when:
    - zabbix_api_host is defined and zabbix_api_host|length > 0
    - zabbix_proxy
  tags:
    - zabbix_api
    - zabbix_api_proxies
