---
- name: zabbix-external | Get Zabbix include configs with templates
  template:
    src: "{{ item }}"
    dest: "{{ zabbix_conf_include_dir }}/{{ item | basename | regex_replace('.j2','') }}"
    owner: "{{ zabbix_user }}"
    group: "{{ zabbix_user }}"
    mode: 0644
  with_fileglob: "{{ zabbix_include_templates|default([]) }}"
  notify: "restart zabbix-{{ zabbix_component }}"

- name: zabbix-external | Get Zabbix include configs from git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest|default(zabbix_conf_include_dir) }}"
    version: "{{ item.version|default(omit) }}"
    clone: "{{ item.clone|default(omit) }}"
    update: "{{ item.update|default(omit) }}"
    separate_git_dir: "{{ item.separate_git_dir|default(omit) }}"
    track_submodules: "{{ item.track_submodules|default(omit) }}"
    remote: "{{ item.remote|default(omit) }}"
    recursive: "{{ item.recursive|default(omit) }}"
    key_file: "{{ item.key_file|default(omit) }}"
    force: "{{ item.force|default(omit) }}"
    executable: "{{ item.executable|default(omit) }}"
    depth: "{{ item.depth|default(omit) }}"
    bare: "{{ item.bare|default(omit) }}"
    accept_hostkey: "{{ item.accept_hostkey|default('yes') }}"
  loop: "{{ zabbix_include_git|default([]) }}"
  notify: "restart zabbix-{{ zabbix_component }}"

- name: zabbix-external | Get Zabbix scripts from templates
  template:
    src: "{{ item }}"
    dest: "{{ zabbix_scripts }}"
    owner: "{{ zabbix_user }}"
    group: "{{ zabbix_user }}"
    mode: 0755
  with_items: "{{ zabbix_scripts_templates|default([]) }}"
  notify: "restart zabbix-{{ zabbix_component }}"

- name: zabbix-external | Get Zabbix scripts from git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest|default(zabbix_scripts) }}"
    version: "{{ item.version|default(omit) }}"
    clone: "{{ item.clone|default(omit) }}"
    update: "{{ item.update|bool|default(true) }}"  # omit does not work there?
    separate_git_dir: "{{ item.separate_git_dir|default(omit) }}"
    track_submodules: "{{ item.track_submodules|default(omit) }}"
    remote: "{{ item.remote|default(omit) }}"
    recursive: "{{ item.recursive|default(omit) }}"
    key_file: "{{ item.key_file|default(omit) }}"
    force: "{{ item.force|default(omit) }}"
    executable: "{{ item.executable|default(omit) }}"
    depth: "{{ item.depth|default(omit) }}"
    bare: "{{ item.bare|default(omit) }}"
    accept_hostkey: "{{ item.accept_hostkey|default('yes') }}"
  loop: "{{ zabbix_scripts_git|default([]) }}"
  notify: "restart zabbix-{{ zabbix_component }}"

- name: zabbix-external | Set up cron job to update cloned git repo for scripts
  cron:
    name: 'Zabbix Update Scripts {{ item.repo }}'
    cron_file: "{{ zabbix_external_cron.file }}"
    user: '{{ zabbix_external_cron.user|default("root") }}'
    hour: '{{ zabbix_external_cron.hour }}'
    minute: '{{ zabbix_external_cron.minute }}'
    day: "{{ zabbix_external_cron.day }}"
    weekday: "{{ zabbix_external_cron.weekday }}"
    month: "{{ zabbix_external_cron.month }}"
    job: 'cd {{ item.dest|default(zabbix_scripts) }} && git pull >/dev/null 2>&1'
  loop: "{{ zabbix_scripts_git|default([]) }}"
  when: zabbix_external_git_cron

- name: zabbix-external | Set up cron job to update cloned git repo for includes
  cron:
    name: 'Zabbix Update Includes {{ item.repo }}'
    cron_file: "{{ zabbix_external_cron.file }}"
    user: "{{ zabbix_external_cron.user }}"
    hour: '{{ zabbix_external_cron.hour }}'
    minute: '{{ zabbix_external_cron.minute }}'
    day: "{{ zabbix_external_cron.day }}"
    weekday: "{{ zabbix_external_cron.weekday }}"
    month: "{{ zabbix_external_cron.month }}"
    job: 'cd {{ item.dest|default(zabbix_conf_include_dir) }} && git pull >/dev/null 2>&1'
  loop: "{{ zabbix_include_git|default([]) }}"
  when: zabbix_external_git_cron
