---
- name: Import Zabbix schema
  mysql_db:
    state: import
    target: "{{ zabbix_component_dbschema }}"
    name: "{{ zabbix_dbname }}"
    login_host: "{{ zabbix_dbhost|default(omit) }}"
    login_password: "{{ zabbix_dbpassword|default(omit) }}"
    login_port: "{{ zabbix_dbport|default(omit) }}"
    login_unix_socket: "{{ zabbix_dbsocket|default(omit) }}"
    login_user: "{{ zabbix_dbuser|default(omit) }}"
  run_once: true
