---
- name: zabbix-proxy | include vars proxy.yml
  include_vars: proxy.yml
  when: zabbix_proxy
  tags:
    - zabbix_install
    - zabbix_config
    - zabbix_proxy
    - zabbix_import
    - zabbix_external

- name: zabbix-proxy | include validate.yml
  include: validate.yml
  tags:
    - zabbix_install
    - zabbix_config
    - zabbix_proxy
    - zabbix_import
    - zabbix_external

- name: zabbix-proxy | include install.yml
  include: install.yml
  tags:
    - zabbix_proxy
    - zabbix_install

- name: zabbix-proxy | include proxy/config.yml
  include: proxy/config.yml
  tags:
    - zabbix_config

- name: zabbix-proxy | include proxy/import.yml
  include: proxy/import.yml
  when: zabbix_proxy_mysql_import
  tags:
    - zabbix_import

- name: zabbix-proxy | include config.yml
  include: config.yml
  tags:
    - zabbix_proxy
    - zabbix_config

- name: zabbix-proxy | include external.yml
  include: external.yml
  tags:
    - zabbix_proxy
    - zabbix_config
    - zabbix_external
