---
- name: zabbix-server | include vars server.yml
  include_vars: server.yml
  when: zabbix_server
  tags: always

- name: zabbix-server | include validate.yml
  include: validate.yml
  tags: always

- name: zabbix-server | include install.yml
  include: install.yml
  tags:
    - zabbix_install

- name: zabbix-server | include server/import.yml
  include: server/import.yml
  when: zabbix_server_mysql_import
  tags:
    - zabbix_import

- name: zabbix-server | include external.yml
  include: external.yml
  tags:
    - zabbix_server
    - zabbix_config
    - zabbix_external
