---
- name: zabbix-server | include vars server.yml
  include_vars: server.yml
  when: zabbix_server
  tags:
    - zabbix_install
    - zabbix_server
    - zabbix_config
    - zabbix_external
    - zabbix_import

- name: zabbix-server | include vars version_5.x.yml
  include_vars: version_5.x.yml
  when: "zabbix_version is version_compare(5.0, '>=')"
  tags:
    - zabbix_install
    - zabbix_server
    - zabbix_config
    - zabbix_external
    - zabbix_import

- name: zabbix-server | include validate.yml
  include: validate.yml
  tags:
    - zabbix_server
    - zabbix_config
    - zabbix_external
    - zabbix_import

- name: zabbix-server | include install.yml
  include: install.yml
  tags:
    - zabbix_install
    - zabbix_server

- name: zabbix-server | include server/import.yml
  include: server/import.yml
  when: zabbix_server_mysql_import
  tags:
    - zabbix_import

- name: zabbix-server | include config.yml
  include: config.yml
  tags:
    - zabbix_server
    - zabbix_config

- name: zabbix-server | include external.yml
  include: external.yml
  tags:
    - zabbix_server
    - zabbix_config
    - zabbix_external
