---
- include_vars: server.yml
  when: zabbix_server
  tags: always

- include: validate.yml
  tags: always

- include: install.yml
  tags:
    - zabbix_install

- include: server/import.yml
  when: zabbix_server_mysql_import
  tags:
    - zabbix_import

- include: external.yml
  tags:
    - zabbix_server
    - zabbix_config
    - zabbix_external
