---
- include: validate.yml

- include: install.yml
  tags:
    - zabbix_install

- include: server/import.yml
  when: zabbix_server_mysql_import
  tags:
    - zabbix_import

# - include: external.yml
#   tags:
#     - zabbix_server
#     - zabbix_config
#     - zabbix_external
