---
- name: Manage Zabbix group
  local_action:
    module: zabbix_group
    server_url: "{{ zabbix_api.url }}"
    login_user: "{{ zabbix_api.username }}"
    login_password: "{{ zabbix_api.password }}"
    host_groups: "{{ zabbix_api_host.groups|join(',') }}"
    state: "{{ zabbix_api_host.state|default(omit) }}"
  when: zabbix_api_host is defined and zabbix_api_host|length > 0

- name: Manage Zabbix hosts
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_api.url }}"
    login_user: "{{ zabbix_api.username }}"
    login_password : "{{ zabbix_api.password }}"
    host_name : "{{ zabbix_api_host.hostname|default(inventory_hostname) }}"
    visible_name: "{{ zabbix_api_host.visible_name|default(omit) }}"
    host_groups: "{{ zabbix_api_host.groups }}"
    link_templates : "{{ zabbix_api_host.templates|default(omit) }}"
    status: "{{ zabbix_api_host.status|default(omit) }}"
    state: "{{ zabbix_api_host.state|default(omit) }}"
    inventory_mode: "{{ zabbix_api_host.inventory_mode|default(omit) }}"
    tls_accept: "{{ zabbix_api_host.tls_accept }}"
    tls_connect: "{{ zabbix_api_host.tls_connect }}"
    tls_psk: "{{ zabbix_agent_psksecret }}"
    tls_psk_identity: "{{ zabbix_agent_pskid }}"
    tls_subject: "{{ zabbix_api_host.tls_subject|default(omit) }}"
    validate_certs: "{{ zabbix_api_host.validate_certs|default(omit) }}"
    interfaces:
      - type: "{{ zabbix_api_host_interfaces.type }}"
        main: "{{ zabbix_api_host_interfaces.main }}"
        useip: "{{ zabbix_api_host_interfaces.useip }}"
        ip: "{{ zabbix_api_host_interfaces.ip }}"
        dns: "{{ zabbix_api_host_interfaces.dns }}"
        port: "{{ zabbix_api_host_interfaces.port }}"
    proxy: "{{ zabbix_api_proxy|default(omit) }}"
    force: "{{ zabbix_api_host.force|default(omit) }}"
  when: zabbix_api_host is defined and zabbix_api_host|length > 0

- name: Manage Zabbix macros
  local_action:
    module: zabbix_hostmacro
    server_url: "{{ zabbix_api.url }}"
    login_user: "{{ zabbix_api.username }}"
    login_password : "{{ zabbix_api.password }}"
    host_name : "{{ zabbix_api_host.hostname|default(inventory_hostname) }}"
    macro_name: "{{ item.key }}"
    macro_value: "{{ item.value }}"
    force: "{{ zabbix_api_host.force|default(omit) }}"
    state: "{{ zabbix_api_host.state|default(omit) }}"
  with_dict: "{{ zabbix_api_macros }}"
  when: zabbix_api_macros is defined and zabbix_api_macros|length > 0
