---
- name: restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes
    daemon_reload: yes
  tags: zabbix-agent

- name: restart zabbix-proxy
  service:
    name: zabbix-proxy
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart zabbix-server
  service:
    name: zabbix-server
    state: restarted
    enabled: yes
    daemon_reload: yes
