---
- name: zabbix-agent | Ensure sudo package
  apt:
    name: sudo
  tags:
    - zabbix_agent
    - zabbix_config

- name: zabbix-agent | Ensure sudoers.d is included in config
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    validate: "/usr/sbin/visudo -cf %s"
  tags:
    - zabbix_agent
    - zabbix_config

- name: zabbix-agent | Add sudo rights
  copy:
    dest: "/etc/sudoers.d/zabbix"
    owner: root
    group: root
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
    content: |
      zabbix ALL=(ALL) NOPASSWD:{{ zabbix_agent_scripts }}/
      {% for item in zabbix_agent_sudo_extra|default([]) %}
      {{ item }}
      {% endfor %}
  tags:
    - zabbix_agent
    - zabbix_config
